services:
  - type: web
    name: trip-itinerary-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production 